# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-1'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/superlinuxex'}
- {icon: 'twitter', link: 'https://twitter.com/superlinuxec'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/leonardo-martínez-alquinga-65b82a8a/'}
- {icon: 'envelope', link: 'mailto:superlinuxec@gmail.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Actuales'
  previous_page: 'Antiguos'

sharing_button_prompt: '¡Sientete libre para compartir!'

related_posts: 'También te puede interesar:'

post_date_prefix: 'Escrito en'
